/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import Conexiones.mysql;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author jaide
 */
public class Login extends javax.swing.JFrame {
    
    mysql cc = new mysql();
    Connection con = cc.conector();
    
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDocumento = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        lblLogin = new javax.swing.JLabel();
        lblDocumento = new javax.swing.JLabel();
        lblContrasena = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblLogin.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        lblLogin.setText("Login");

        lblDocumento.setText("Documento");

        lblContrasena.setText("Contraseña");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(lblLogin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(lblDocumento))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(lblContrasena))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDocumento)
                            .addComponent(txtPass, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(lblDocumento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblContrasena)
                .addGap(3, 3, 3)
                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        validarUsuario();

    }//GEN-LAST:event_btnLoginActionPerformed
    
    public void validarUsuario(){
        boolean resultado = false;
        String pass = String.valueOf(txtPass.getPassword());
        String usr = txtDocumento.getText();
        String SQL_Adm ="SELECT `id_adm`, `pass_adm` FROM `admin` WHERE `id_adm`='"+usr+"' AND `pass_adm`='"+pass+"'";
        String SQL_Practicante ="SELECT `id_practicante`,`pass_practicante` FROM `practicante` WHERE `id_practicante`='"+usr+"' AND `pass_practicante` ='"+pass+"'";
        String SQL_Encargado ="SELECT `id_encargado`, `pass_encargado` FROM `encargado` WHERE `id_encargado`='"+usr+"' AND `pass_encargado` ='"+pass+"'";
        
        try {
            Statement st_adm = con.createStatement();
            ResultSet rs_adm = st_adm.executeQuery(SQL_Adm);
            
            if (rs_adm.next()) {
                resultado = true;
                if (resultado == true) {
                    InterfazAdm adm = new InterfazAdm();
                    adm.setVisible(true);
                    this.dispose();
                }
            
            
            }else{
                
                        try {
                            Statement st_encargado = con.createStatement();
                            ResultSet rs_encargado = st_encargado.executeQuery(SQL_Encargado);

                            if (rs_encargado.next()) {
                                resultado = true;
                                if (resultado == true) {
                                    JOptionPane.showMessageDialog(null, "Encargado Logueado");
                                  /*  InterfazAdm adm = new InterfazAdm();
                                    adm.setVisible(true);
                                    this.dispose(); */
                                }


                            }else{
                                
                                        try {
                                            Statement st_practicante = con.createStatement();
                                            ResultSet rs_practicante = st_practicante.executeQuery(SQL_Practicante);

                                            if (rs_practicante.next()) {
                                                resultado = true;
                                                if (resultado == true) {
                                                    JOptionPane.showMessageDialog(null, "Practicante Logueado");
                                                   /* InterfazAdm adm = new InterfazAdm();
                                                    adm.setVisible(true);
                                                    this.dispose();*/
                                                }


                                            }else{
                                                JOptionPane.showMessageDialog(null, "Usuario no Registrado");
                                            }
                                        } catch (Exception e) {
                                            JOptionPane.showMessageDialog(null, "Error "+e.getMessage());
                                        }
                                
                            }
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(null, "Error "+e.getMessage());
                        }
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error "+e.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblDocumento;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables
}
